### ISSUE TITLE
Authentication with OAuth/Personal Access Tokens

### ISSUE THREAD

**Issue by AndyOGo** [pocketworks/git2pdf#11]
I have setup access tokens for a private github accounts but can't get it to authenticate properly :(

As described in:
https://developer.github.com/enterprise/2.7/v3/auth/#basic-authentication

````sh
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 401 Unauthorized (OpenURI::HTTPError)
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git2pdf-0.1.5/lib/git2pdf.rb:29:in `block in get_issues'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git2pdf-0.1.5/lib/git2pdf.rb:22:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git2pdf-0.1.5/lib/git2pdf.rb:22:in `get_issues'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git2pdf-0.1.5/lib/git2pdf.rb:16:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git2pdf-0.1.5/bin/git2pdf:29:in `gen'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git2pdf-0.1.5/bin/git2pdf:36:in `<top (required)>'
	from /usr/local/bin/git2pdf:22:in `load'
	from /usr/local/bin/git2pdf:22:in `<main>'
````

**Comment by wordswords** [comment]
I have a pull request pending that will fix this.. just not sure if this project is actively maintained anymore

**Comment by AndyOGo** [comment]
@wordswords 
Yeah it's definitely not maintained since 2015.
I had to install from git source to make #12 work...

@tobinharris 
Any plans on working on this?

**Comment by tobinharris** [comment]
Hi @AndyOGo / @wordswords 

Still fond of the project but we're currently on JIRA so not using this enough. Would be happy to find a new maintainer for the repo if there are any volunteers.
