### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by ThierryBegin** [pocketworks/git2pdf#3]
C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certif
icate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:716:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:34:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/git2pdf-0.1.5/lib/git2pdf.rb:29:in `block in get_issues'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/git2pdf-0.1.5/lib/git2pdf.rb:22:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/git2pdf-0.1.5/lib/git2pdf.rb:22:in `get_issues'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/git2pdf-0.1.5/lib/git2pdf.rb:16:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/git2pdf-0.1.5/bin/git2pdf:29:in `gen'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/git2pdf-0.1.5/bin/git2pdf:36:in `<top (required)>'
        from C:/Ruby22-x64/bin/git2pdf:23:in `load'
        from C:/Ruby22-x64/bin/git2pdf:23:in `<main>'

**Comment by sebnor** [comment]
+1

**Comment by YutingTang** [comment]
+1

**Comment by seyyah** [comment]
workaround solution for Ubuntu 16.04,

```sh
$ wget http://curl.haxx.se/ca/cacert.pem
$ sudo mv cacert.pem /usr/local/share/ca-certificates/
$ #Add export SSL_CERT_FILE=/usr/local/share/ca-certificates/cacert.pem to your .bash_profile
$ echo "export SSL_CERT_FILE=/usr/local/share/ca-certificates/cacert.pem" >> ~/.bash_profile
$ source ~/.bash_profile
$ # test
$ echo $SSL_CERT_FILE
/usr/local/share/ca-certificates/cacert.pem
```
References
- https://github.com/google/google-api-ruby-client/issues/253
- http://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu
